Add cronjob for backup database

diff --git a/manifests/home-assistant/manifest.yaml b/manifests/home-assistant/manifest.yaml
--- a/manifests/home-assistant/manifest.yaml
+++ b/manifests/home-assistant/manifest.yaml
@@ -52,6 +52,38 @@ spec:
       provisioner_driver: node-manual
 
 ---
+kind: PersistentVolume
+apiVersion: v1
+metadata:
+  name: pv-nfs-home-assistant-backups
+  labels:
+    app.kubernetes.io/name: backups
+    app.kubernetes.io/component: cronjob
+    app.kubernetes.io/instance: production
+    app.kubernetes.io/part-of: home-assistant
+spec:
+  storageClassName: "freenas-nfs-manual-csi"
+  capacity:
+    storage: 500Gi
+  accessModes:
+    - ReadWriteMany
+  persistentVolumeReclaimPolicy: Retain
+  mountOptions:
+    - nfsvers=4
+    - nolock
+    - noatime
+  csi:
+    driver: org.democratic-csi.node-manual
+    readOnly: false
+    fsType: nfs
+    volumeHandle: pv-nfs-home-assistant-backups
+    volumeAttributes:
+      server: storage-server-lagg.lan.theautomation.nl
+      share: /mnt/r10_8tb/backups
+      node_attach_driver: nfs
+      provisioner_driver: node-manual
+
+---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
@@ -65,6 +97,26 @@ spec:
     requests:
       storage: 5Gi
   volumeName: pv-nfs-home-assistant-config
+
+---
+kind: PersistentVolumeClaim
+apiVersion: v1
+metadata:
+  name: pvc-nfs-home-assistant-backups
+  namespace: home-automation
+  labels:
+    app.kubernetes.io/name: backups
+    app.kubernetes.io/component: cronjob
+    app.kubernetes.io/instance: production
+    app.kubernetes.io/part-of: home-assistant
+spec:
+  storageClassName: freenas-nfs-manual-csi
+  accessModes:
+    - ReadWriteMany
+  resources:
+    requests:
+      storage: 500Gi
+  volumeName: pv-nfs-home-assistant-backups
 
 ---
 kind: SealedSecret
@@ -128,6 +180,33 @@ spec:
       namespace: home-automation
 
 ---
+kind: ConfigMap
+apiVersion: v1
+metadata:
+  name: backup-script-postgresql
+  namespace: home-automation
+  labels:
+    app.kubernetes.io/name: backups
+    app.kubernetes.io/component: cronjob
+    app.kubernetes.io/instance: production
+    app.kubernetes.io/part-of: home-assistant
+data:
+  pg_backup.sh: |-
+    #!/bin/bash
+
+    DATE=$(date +%Y%m%d-%H%M)
+    DEST="/mnt/backups/${APP_NAME}/database"
+    FILENAME="${DATE}_${PG_DATABASE}.sql"
+    ERROR_LOG="${DEST}/${FILENAME}.error.log"
+
+    if PGPASSWORD="${PG_PASSWORD}" pg_dump --verbose --inserts --column-inserts --username="${PG_USERNAME}" --host="${PG_HOST}" --port="${PG_PORT}" "${PG_DATABASE}" > "${DEST}/${FILENAME}"; then
+      echo "Database backup successful: ${DEST}/${FILENAME}"
+    else
+      echo "Error: Database backup failed" > "${ERROR_LOG}"
+      exit 1
+    fi
+
+---
 kind: StatefulSet
 apiVersion: apps/v1
 metadata:
@@ -169,7 +248,7 @@ spec:
       hostIPC: false
       containers:
         - name: postgresql
-          image: "bitnami/postgresql:14.5.0"
+          image: "bitnami/postgresql:14"
           imagePullPolicy: "IfNotPresent"
           securityContext:
             runAsUser: 1000
@@ -264,7 +343,7 @@ spec:
     spec:
       initContainers:
         - name: postgresql-isready
-          image: "bitnami/postgresql:14.5.0"
+          image: "bitnami/postgresql:14"
           env:
             - name: POSTGRESQL_USERNAME
               valueFrom:
@@ -322,6 +401,73 @@ spec:
             secretName: secrets
       imagePullSecrets:
         - name: github-registry-creds
+
+---
+apiVersion: batch/v1
+kind: CronJob
+metadata:
+  name: home-assistant-db-backup
+  namespace: home-automation
+  labels:
+    app.kubernetes.io/name: backups
+    app.kubernetes.io/component: cronjob
+    app.kubernetes.io/instance: production
+    app.kubernetes.io/part-of: home-assistant
+spec:
+  schedule: "0 12 * * *"
+  jobTemplate:
+    spec:
+      template:
+        spec:
+          securityContext:
+            fsGroup: 1000
+          containers:
+            - name: postgres-backup
+              image: postgres:14
+              securityContext:
+                runAsUser: 1000
+              command:
+                - "/tmp/pg_backup.sh"
+              env:
+                - name: APP_NAME
+                  valueFrom:
+                    secretKeyRef:
+                      name: home-assistant-postgresql-secret
+                      key: postgresql-username
+                - name: PG_DATABASE
+                  valueFrom:
+                    secretKeyRef:
+                      name: home-assistant-postgresql-secret
+                      key: postgresql-username
+                - name: PG_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: home-assistant-postgresql-secret
+                      key: postgresql-password
+                - name: PG_USERNAME
+                  valueFrom:
+                    secretKeyRef:
+                      name: home-assistant-postgresql-secret
+                      key: postgresql-username
+                - name: PG_HOST
+                  value: "home-assistant-postgresql-hl"
+                - name: PG_PORT
+                  value: "5432"
+              volumeMounts:
+                - name: backups
+                  mountPath: /mnt/backups
+                - name: backup-script
+                  mountPath: /tmp
+              resources: {}
+          volumes:
+            - name: backups
+              persistentVolumeClaim:
+                claimName: pvc-nfs-home-assistant-backups
+            - name: backup-script
+              configMap:
+                name: backup-script-postgresql
+                defaultMode: 0755
+          restartPolicy: Never
 
 ---
 kind: Service
